### ISSUE TITLE
Notice of Copyright/License Violation

### ISSUE THREAD

**Issue by Fuzzbawls** [Nitrous-Core/nitrous#11]
This is a notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license has been modified to explicitely exclude the PIVX developers' copyright.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository.

**Comment by Nitrous-Core** [comment]
Can you please explain what you feel is in violation of copyright?  If so, we'd be happy to correct it.

We haven't modified the MIT license in any way.

The project was not forked from PIVX directly and all copyrights that were in the original code remain here.  If the issue is that there is no PIVX copyright displayed, we will correct that over the next few days.

**Comment by Fuzzbawls** [comment]
https://github.com/Nitrous-Core/nitrous/blob/master/COPYING

You have explicitly removed the required PIVX copyright from the license/use agreement file. That file (and all the source code headers) are binding; meaning that any removal or editing of prior copyrights is against the use license.

**Comment by Nitrous-Core** [comment]
I understand what you are saying be WE didn't remove it.  We forked the code from another project - Wilo - and all copyrights that were in place when we forked it remained in place.  We would have no reason to "explicitly remove" a PIVX copyright (which appears everywhere else in our software).  If you are saying the copyright is missing specifically from the MIT license file, I see that and I have corrected it.

Again, we removed nothing related to copyrights.  We forked the code from a different project.  If something was removed, it was prior to our fork.  Therefore, I can't be 100% sure what you want me to add.  For now, I have added PIVX to the license page, but if there are other places PIVX should be mentioned and it is not, you'll need to tell me where those places are.  Thanks.

PS.  After reading the accusatory tone of your message again, I'd like to make it clear that WE DID NOT MODIFY THE LICENSE FILE.  **WE** DID NOT EXPLICITLY REMOVE ANYTHING. HOWEVER, WE ARE WILLING TO ENTERTAIN YOUR REQUEST AND CORRECT WHAT SOMEBODY UPSTREAM DID.  That is unless you accuse us again of "explicitly removing the required PIVX copyright".  A little manners would go a long way.

**Comment by Fuzzbawls** [comment]
I understand your dilemma and your response, but the fact remains that your source code is in violation of a particular copyright, and it is your responsibility to correct it, even if the source you forked from is also in violation.

I do see that you have corrected the situation in https://github.com/Nitrous-Core/nitrous/commit/dc6c9b04083e736205e8ea47f87a2b113fc314f3 and will thus close this issue and consider it resolved for your part, though I would ask that you provide me a link to the source repository you forked from so I can address the issue there as well.

**Comment by Nitrous-Core** [comment]
https://github.com/WiloTeam/Wilo

Doesn't seem to be much there now.

**Comment by Fuzzbawls** [comment]
Ok, yep...looks like a dead/scam project.

You have resolved the issue on your own, so that is all that is required at this point. Regarding your edit to your above comment: it doesn't matter where you sourced/forked from; all open source projects are inherently liable for any and all copyright or license/use stipulations.

Had you forked the PIVX repository directly, this likely would not have been an issue at all, but a copy of a copy is still responsible for any and all original copyrights or use licenses even if said copyrights/licenses have been altered elsewhere. The only thing that we (PIVX) can operate on when a project doesn't follow github's forking guidelines is the source at hand (ie, we are not aware of the fact you copied the source from a 3rd party), and so any modifications to the copyright/license are inherited by your project.

**Comment by Nitrous-Core** [comment]
Understood.  But the same logic applies to the person forking the source code - they would have absolutely no way of knowing that there is a missing copyright unless they are told.  PIVX isn't in *every* Github project.  If the project I'm forking from doesn't mention PIVX, It *should* be safe to assume that PIVX didn't create any of it (ie, we are not aware of the fact that the source we copied was a "3rd party").  I appreciate you bringing this to our attention so that we could fix it.  In the future though, I would suggest approaching with a more cooperative attitude.  We both know that the language you used was a bit dramatic for a copyright missing in **ONE** text file.  It appears everywhere else. And although I'm not an attorney, the copyright in that specific place seems hardly worth mentioning. You must have been looking pretty hard to find something so insignificant.
